/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package visualalgo;

import java.security.AlgorithmConstraints;

import visualalgo.controllers.AlgorithmController;
import visualalgo.views.mainFrame;

public class App {

    public static void main(String[] args) {
        
        AlgorithmController controller = new AlgorithmController();

        mainFrame main = new mainFrame(controller);

    }
}
